ADMIN_HTML = r'''<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width,initial-scale=1" />
<title>orby4middleware Console</title>
<style>
:root{--bg:#f6f8fb;--panel:#fff;--text:#172033;--muted:#667085;--line:#dfe5ee;--brand:#2447d8;--ok:#157f3b;--warn:#a15c00;--bad:#b42318}
*{box-sizing:border-box}body{margin:0;font-family:Inter,ui-sans-serif,system-ui,-apple-system,Segoe UI,sans-serif;background:var(--bg);color:var(--text)}
header{height:64px;background:#101828;color:white;display:flex;align-items:center;justify-content:space-between;padding:0 24px;position:sticky;top:0;z-index:5}
header b{font-size:20px}header small{color:#cfd6e4}.shell{display:grid;grid-template-columns:230px 1fr;min-height:calc(100vh - 64px)}
nav{background:#fff;border-right:1px solid var(--line);padding:18px 12px}nav button{width:100%;border:0;background:transparent;text-align:left;padding:11px 12px;border-radius:8px;margin:2px 0;font-size:14px;cursor:pointer}nav button.active,nav button:hover{background:#eef2ff;color:var(--brand)}
main{padding:26px;max-width:1500px}.view{display:none}.view.active{display:block}.topline{display:flex;align-items:center;justify-content:space-between;gap:16px;margin-bottom:18px}
h1{font-size:26px;margin:0}h2{font-size:18px;margin:0 0 14px}h3{font-size:15px;margin:0 0 10px}.muted{color:var(--muted)}
.grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:14px}.card{background:var(--panel);border:1px solid var(--line);border-radius:12px;padding:18px}.metric{font-size:28px;font-weight:700;margin-top:8px}
button.primary,button.secondary,button.danger{border-radius:8px;padding:9px 13px;font-weight:600;cursor:pointer}.primary{border:1px solid var(--brand);background:var(--brand);color:#fff}.secondary{border:1px solid var(--line);background:#fff;color:var(--text)}.danger{border:1px solid #f0b5b0;background:#fff;color:var(--bad)}
input,select,textarea{width:100%;border:1px solid #cfd7e3;border-radius:8px;padding:9px 10px;background:#fff;color:var(--text)}textarea{min-height:110px;font-family:ui-monospace,SFMono-Regular,Consolas,monospace}label{font-size:12px;color:var(--muted);display:block;margin-bottom:5px}.field{margin-bottom:13px}.row{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:13px}.row3{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:13px}
table{width:100%;border-collapse:collapse;font-size:13px}th,td{padding:9px 8px;border-bottom:1px solid var(--line);text-align:left;vertical-align:top}th{color:var(--muted);font-weight:600}.pill{display:inline-block;border-radius:999px;padding:3px 8px;font-size:11px;background:#eef2f6}.pill.ok{background:#e9f8ee;color:var(--ok)}.pill.warn{background:#fff4e5;color:var(--warn)}.pill.bad{background:#fdecea;color:var(--bad)}
.steps{display:flex;gap:8px;flex-wrap:wrap;margin-bottom:16px}.step{border:1px solid var(--line);background:#fff;padding:8px 10px;border-radius:999px;font-size:12px;cursor:pointer}.step.active{border-color:var(--brand);background:#eef2ff;color:var(--brand)}.wizard-pane{display:none}.wizard-pane.active{display:block}.toolbar{display:flex;gap:8px;flex-wrap:wrap;align-items:center}.error{padding:10px;border:1px solid #f2b8b5;background:#fff3f2;color:var(--bad);border-radius:8px;margin:10px 0;white-space:pre-wrap}.success{padding:10px;border:1px solid #a6ddb6;background:#edf9f0;color:var(--ok);border-radius:8px;margin:10px 0}.hidden{display:none!important}.codebox{white-space:pre-wrap;background:#111827;color:#d1e7ff;border-radius:8px;padding:12px;max-height:260px;overflow:auto;font-size:12px}.section{margin-top:18px}.api-key{display:flex;gap:8px;align-items:center}.api-key input{width:260px}.narrow{max-width:820px}.table-wrap{overflow:auto}.help{font-size:12px;color:var(--muted);margin-top:4px}.split{display:grid;grid-template-columns:1fr 1fr;gap:16px}
@media(max-width:900px){.shell{grid-template-columns:1fr}nav{display:flex;overflow:auto;border-right:0;border-bottom:1px solid var(--line)}nav button{min-width:120px}.grid{grid-template-columns:1fr 1fr}.row,.row3,.split{grid-template-columns:1fr}main{padding:16px}}
</style>
</head>
<body>
<header><div><b>orby4middleware</b> <small>Medical Device Integration Gateway</small></div><div class="api-key"><input id="apiKey" type="password" placeholder="X-API-Key"/><button class="secondary" onclick="saveKey()">Use key</button></div></header>
<div class="shell">
<nav>
<button class="active" data-view="overview">Overview</button>
<button data-view="devices">Devices</button>
<button data-view="onboard">Onboard device</button>
<button data-view="orders">Orders / accessions</button>
<button data-view="results">Results</button>
<button data-view="deliveries">Deliveries</button>
</nav>
<main>
<section id="overview" class="view active"><div class="topline"><div><h1>Gateway overview</h1><div class="muted">Operational status across devices, matching and EMR delivery.</div></div><button class="secondary" onclick="refreshAll()">Refresh</button></div><div id="overviewCards" class="grid"></div><div class="card section"><h2>Clinical safety state</h2><p>Unmatched accessions remain held. Enabling automatic delivery requires a successful parse preview and a non-experimental validation state.</p></div></section>

<section id="devices" class="view"><div class="topline"><div><h1>Devices</h1><div class="muted">Configured instruments, platforms and modalities.</div></div><button class="primary" onclick="showView('onboard')">Add device</button></div><div class="card table-wrap"><table><thead><tr><th>Device</th><th>Manufacturer / model</th><th>Protocol</th><th>Validation</th><th>Preview</th><th>Delivery</th><th></th></tr></thead><tbody id="deviceRows"></tbody></table></div></section>

<section id="onboard" class="view"><div class="topline"><div><h1>Device onboarding</h1><div class="muted">Identity → connection → parser → preview/mapping → validation/delivery.</div></div></div><div class="steps"><button class="step active" data-step="1">1 Identity</button><button class="step" data-step="2">2 Connection</button><button class="step" data-step="3">3 Parser</button><button class="step" data-step="4">4 Preview & mapping</button><button class="step" data-step="5">5 Validate & deliver</button></div><div id="wizardMessage"></div>
<div class="card narrow">
<div class="wizard-pane active" data-pane="1"><h2>Identity and profile</h2><div class="row"><div class="field"><label>Device key</label><input id="deviceKey" placeholder="lab-haematology-01"/></div><div class="field"><label>Manufacturer</label><select id="manufacturer"></select></div></div><div class="row"><div class="field"><label>Model</label><input id="model" list="modelSuggestions" placeholder="BC-3000 Plus"/><datalist id="modelSuggestions"></datalist></div><div class="field"><label>Base profile</label><select id="profile"></select></div></div><div class="help">Select the closest documented profile. Generic profiles are intended for legacy devices whose interface manuals describe field layout or standard ASTM/HL7 behavior.</div><div class="toolbar section"><button class="primary" onclick="createOrSelectDevice()">Save identity</button><button class="secondary" onclick="goStep(2)">Next</button></div></div>
<div class="wizard-pane" data-pane="2"><h2>Connection</h2><div class="field"><label>Transport</label><select id="transport" onchange="renderConnectionFields()"><option value="serial">RS-232 / serial</option><option value="tcp">TCP socket</option><option value="mllp">HL7 MLLP</option><option value="http">HTTP / REST</option><option value="fhir">FHIR HTTP</option><option value="dicom">DICOM / DICOMweb</option><option value="file">File / CSV drop</option></select></div><div id="connectionFields"></div><div class="toolbar"><button class="primary" onclick="saveConnection()">Save connection</button><button class="secondary" onclick="goStep(3)">Next</button></div></div>
<div class="wizard-pane" data-pane="3"><h2>Parser configuration</h2><div id="parserSummary" class="card" style="padding:12px;margin-bottom:12px"></div><div id="fixedWidthEditor" class="hidden"><div class="row"><div class="field"><label>Accession start</label><input id="accessionStart" type="number" value="0"/></div><div class="field"><label>Accession end</label><input id="accessionEnd" type="number" value="8"/></div></div><h3>Fixed-width result fields</h3><div class="table-wrap"><table><thead><tr><th>Code</th><th>Start</th><th>End</th><th>Unit</th><th>LOINC</th><th></th></tr></thead><tbody id="fixedRows"></tbody></table></div><button class="secondary" onclick="addFixedRow()">Add field</button></div><div id="delimitedEditor" class="hidden"><div class="row3"><div class="field"><label>Record separator</label><input id="recordSeparator" value="\\r"/></div><div class="field"><label>Field separator</label><input id="fieldSeparator" value="|"/></div><div class="field"><label>Sample record marker</label><input id="sampleRecord" value="S"/></div></div><div class="row3"><div class="field"><label>Accession index</label><input id="accessionIndex" type="number" value="1"/></div><div class="field"><label>Result record marker</label><input id="resultRecord" value="R"/></div><div class="field"><label>Code / value / unit indexes</label><input id="resultIndexes" value="1,2,3,4"/></div></div></div><div id="regexEditor" class="hidden"><div class="field"><label>Accession regex</label><input id="accessionRegex"/></div><div class="field"><label>Result regex</label><textarea id="resultRegex"></textarea></div></div><div class="field"><label>Advanced parser config JSON</label><textarea id="parserJson" placeholder='{"accession_field":"accession","results_field":"results"}'></textarea><div class="help">Optional. Values here merge over the visual fields above.</div></div><div class="toolbar"><button class="primary" onclick="saveParser()">Save parser</button><button class="secondary" onclick="goStep(4)">Next</button></div></div>
<div class="wizard-pane" data-pane="4"><h2>Capture / parse preview</h2><div class="field"><label>Sample device payload</label><textarea id="previewPayload" placeholder="Paste a de-identified analyzer frame, ASTM/HL7 message, JSON or FHIR Bundle"></textarea></div><div class="toolbar"><button class="primary" onclick="runPreview()">Test parse</button></div><div id="previewOutput" class="section"></div><div id="mappingEditor" class="section hidden"><h3>Result mapping</h3><div class="help">Map source codes to standard display/code, LOINC and unit. Disable a row only when that result must not be forwarded.</div><div class="table-wrap"><table><thead><tr><th>Source</th><th>Enabled</th><th>Target code</th><th>Display</th><th>LOINC</th><th>Unit</th></tr></thead><tbody id="mappingRows"></tbody></table></div><div class="toolbar section"><button class="primary" onclick="saveMapping()">Save mapping</button><button class="secondary" onclick="goStep(5)">Next</button></div></div></div>
<div class="wizard-pane" data-pane="5"><h2>Validation and EMR delivery</h2><div id="gateState" class="section"></div><div class="row"><div class="field"><label>Validation status</label><select id="validationStatus"><option value="experimental">experimental</option><option value="vendor-documented">vendor-documented</option><option value="validated-lab">validated-lab</option></select></div><div class="field"><label>Validated by</label><input id="validatedBy" placeholder="Operator / biomedical engineer"/></div></div><div class="field"><label>Validation notes</label><textarea id="validationNotes" placeholder="Interface manual version, firmware, sample frames, comparison checks..."></textarea></div><button class="secondary" onclick="saveValidation()">Save validation</button><hr style="border:0;border-top:1px solid var(--line);margin:20px 0"/><div class="row3"><div class="field"><label>Target type</label><select id="targetType"><option value="fhir">FHIR</option><option value="hl7">HL7 v2 / MLLP</option><option value="rest">REST / JSON</option></select></div><div class="field"><label>Target</label><input id="target" placeholder="https://emr.example/fhir or host:port"/></div><div class="field"><label>Automatic delivery</label><select id="deliveryEnabled"><option value="false">Disabled</option><option value="true">Enabled</option></select></div></div><button class="primary" onclick="saveDelivery()">Save delivery settings</button></div>
</div></section>

<section id="orders" class="view"><div class="topline"><div><h1>Orders / accessions</h1><div class="muted">Exact specimen-to-patient mapping. No fuzzy patient matching.</div></div></div><div class="split"><div class="card"><h2>Add or update mapping</h2><div class="field"><label>Accession / sample ID</label><input id="orderAccession"/></div><div class="field"><label>Patient ID</label><input id="patientId"/></div><div class="field"><label>Encounter ID</label><input id="encounterId"/></div><div class="field"><label>FHIR ServiceRequest ID</label><input id="serviceRequestId"/></div><button class="primary" onclick="saveOrder()">Save mapping</button></div><div class="card table-wrap"><table><thead><tr><th>Accession</th><th>Patient</th><th>Encounter</th><th>ServiceRequest</th></tr></thead><tbody id="orderRows"></tbody></table></div></div></section>
<section id="results" class="view"><div class="topline"><div><h1>Results</h1><div class="muted">Normalized results and matching state.</div></div><button class="secondary" onclick="loadResults()">Refresh</button></div><div class="card table-wrap"><table><thead><tr><th>ID</th><th>Device</th><th>Accession</th><th>Patient</th><th>Status</th><th>Observed</th><th>Results</th></tr></thead><tbody id="resultRows"></tbody></table></div></section>
<section id="deliveries" class="view"><div class="topline"><div><h1>Delivery attempts</h1><div class="muted">FHIR, HL7/MLLP and REST delivery history.</div></div><button class="secondary" onclick="loadDeliveries()">Refresh</button></div><div class="card table-wrap"><table><thead><tr><th>ID</th><th>Result</th><th>Target</th><th>Attempt</th><th>Status</th><th>Response</th></tr></thead><tbody id="deliveryRows"></tbody></table></div></section>
</main></div>
<script>
let catalogData={};let devices=[];let selectedDevice=null;let lastPreview=null;
const $=id=>document.getElementById(id);const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function key(){return sessionStorage.getItem('orbyApiKey')||''}function saveKey(){sessionStorage.setItem('orbyApiKey',$('apiKey').value);refreshAll()}
async function api(path,opts={}){const headers={'Content-Type':'application/json',...(opts.headers||{})};if(key())headers['X-API-Key']=key();const r=await fetch(path,{...opts,headers});let body;try{body=await r.json()}catch{body=await r.text()}if(!r.ok)throw new Error(typeof body==='string'?body:(body.detail||JSON.stringify(body)));return body}
function msg(text,ok=true){$('wizardMessage').innerHTML=`<div class="${ok?'success':'error'}">${esc(text)}</div>`}
function showView(id){document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));$(id).classList.add('active');document.querySelectorAll('nav button').forEach(x=>x.classList.toggle('active',x.dataset.view===id));if(id==='devices')loadDevices();if(id==='orders')loadOrders();if(id==='results')loadResults();if(id==='deliveries')loadDeliveries()}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>showView(b.dataset.view));document.querySelectorAll('.step').forEach(b=>b.onclick=()=>goStep(+b.dataset.step));
function goStep(n){document.querySelectorAll('.wizard-pane').forEach(x=>x.classList.toggle('active',+x.dataset.pane===n));document.querySelectorAll('.step').forEach(x=>x.classList.toggle('active',+x.dataset.step===n));if(n===3)renderParserEditor();if(n===5)renderGate()}
function validationPill(s){const c=s==='validated-lab'||s==='DELIVERED'?'ok':s==='vendor-documented'||s==='MATCHED'?'warn':'bad';return `<span class="pill ${c}">${esc(s)}</span>`}
async function loadCatalog(){catalogData=await api('/api/v1/catalog');const names=[...new Set(Object.values(catalogData.manufacturers||{}).flat())];$('manufacturer').innerHTML=names.map(x=>`<option>${esc(x)}</option>`).join('');$('profile').innerHTML=(catalogData.profiles||[]).map(p=>`<option value="${esc(p.id)}">${esc(p.manufacturer)} — ${esc(p.model)} [${esc(p.protocol)}]</option>`).join('');$('profile').onchange=profileChanged;profileChanged()}
function profileChanged(){const p=(catalogData.profiles||[]).find(x=>x.id===$('profile').value);if(!p)return;$('manufacturer').value=p.manufacturer||$('manufacturer').value;if(!$('model').value)$('model').value=p.model||'';$('modelSuggestions').innerHTML=(catalogData.profiles||[]).filter(x=>x.manufacturer===$('manufacturer').value).map(x=>`<option value="${esc(x.model)}"></option>`).join('');renderParserEditor()}
async function loadDevices(){devices=await api('/api/v1/devices');$('deviceRows').innerHTML=devices.map(d=>{const ob=d.config?.onboarding||{},del=d.config?.delivery||{};return `<tr><td><b>${esc(d.device_key)}</b></td><td>${esc(d.manufacturer)}<br><span class="muted">${esc(d.model)}</span></td><td>${esc(d.protocol||'')}</td><td>${validationPill(d.validation_status)}</td><td>${ob.preview_ok?'<span class="pill ok">passed</span>':'<span class="pill warn">not passed</span>'}</td><td>${del.enabled?'<span class="pill ok">enabled</span>':'<span class="pill">disabled</span>'}</td><td><button class="secondary" onclick="editDevice(${d.id})">Configure</button></td></tr>`}).join('')}
async function refreshAll(){try{await Promise.all([loadCatalog(),loadDevices(),loadOrders(),loadResults(),loadDeliveries()]);const unmatched=(window._results||[]).filter(x=>x.status==='UNMATCHED').length,failed=(window._deliveries||[]).filter(x=>x.status==='FAILED').length;$('overviewCards').innerHTML=`<div class="card"><div class="muted">Devices</div><div class="metric">${devices.length}</div></div><div class="card"><div class="muted">Validated lab</div><div class="metric">${devices.filter(x=>x.validation_status==='validated-lab').length}</div></div><div class="card"><div class="muted">Unmatched results</div><div class="metric">${unmatched}</div></div><div class="card"><div class="muted">Failed deliveries</div><div class="metric">${failed}</div></div>`}catch(e){$('overviewCards').innerHTML=`<div class="error">${esc(e.message)}</div>`}}
async function createOrSelectDevice(){try{const body={device_key:$('deviceKey').value.trim(),manufacturer:$('manufacturer').value,model:$('model').value.trim(),profile_id:$('profile').value};if(!body.device_key||!body.model)throw new Error('Device key and model are required');selectedDevice=await api('/api/v1/devices',{method:'POST',body:JSON.stringify(body)});msg('Device identity saved.');await loadDevices();goStep(2)}catch(e){msg(e.message,false)}}
async function editDevice(id){try{selectedDevice=await api(`/api/v1/devices/${id}`);$('deviceKey').value=selectedDevice.device_key;$('manufacturer').value=selectedDevice.manufacturer;$('model').value=selectedDevice.model;$('profile').value=selectedDevice.profile_id;hydrateDevice();showView('onboard');goStep(2)}catch(e){msg(e.message,false)}}
function hydrateDevice(){const c=selectedDevice?.config||{},conn=c.connection||{},del=c.delivery||{},onb=c.onboarding||{};$('transport').value=conn.transport||'serial';renderConnectionFields(conn);$('validationStatus').value=selectedDevice.validation_status||'experimental';$('validatedBy').value=onb.validated_by||'';$('validationNotes').value=onb.validation_notes||'';$('targetType').value=del.target_type||'fhir';$('target').value=del.target||'';$('deliveryEnabled').value=String(!!del.enabled);renderParserEditor();renderGate()}
function ensureDevice(){if(!selectedDevice)throw new Error('Save or select a device first')}
function renderConnectionFields(c={}){const t=$('transport').value;let html='';if(t==='serial')html=`<div class="row3"><div class="field"><label>Port</label><input id="connPort" value="${esc(c.port||'COM3')}"/></div><div class="field"><label>Baud</label><input id="connBaud" type="number" value="${esc(c.baud||9600)}"/></div><div class="field"><label>Data bits</label><input id="connDataBits" type="number" value="${esc(c.data_bits||8)}"/></div></div><div class="row"><div class="field"><label>Parity</label><select id="connParity"><option>None</option><option>Even</option><option>Odd</option></select></div><div class="field"><label>Stop bits</label><input id="connStopBits" value="${esc(c.stop_bits||1)}"/></div></div>`;else if(['tcp','mllp'].includes(t))html=`<div class="row"><div class="field"><label>Host</label><input id="connHost" value="${esc(c.host||'')}"/></div><div class="field"><label>Port</label><input id="connTcpPort" type="number" value="${esc(c.port||'')}"/></div></div>`;else if(['http','fhir'].includes(t))html=`<div class="field"><label>Base URL</label><input id="connUrl" value="${esc(c.url||'')}" placeholder="https://device-or-platform.example/api"/></div>`;else if(t==='dicom')html=`<div class="row"><div class="field"><label>AE Title</label><input id="connAe" value="${esc(c.ae_title||'ORBY')}"/></div><div class="field"><label>DICOMweb URL / Orthanc</label><input id="connUrl" value="${esc(c.url||'http://orthanc:8042/dicom-web')}"/></div></div>`;else html=`<div class="field"><label>Watch path</label><input id="connPath" value="${esc(c.path||'')}"/></div>`;$('connectionFields').innerHTML=html}
function collectConnection(){const t=$('transport').value,c={transport:t};if(t==='serial')Object.assign(c,{port:$('connPort').value,baud:+$('connBaud').value,data_bits:+$('connDataBits').value,parity:$('connParity').value,stop_bits:+$('connStopBits').value});else if(['tcp','mllp'].includes(t))Object.assign(c,{host:$('connHost').value,port:+$('connTcpPort').value});else if(['http','fhir'].includes(t))c.url=$('connUrl').value;else if(t==='dicom')Object.assign(c,{ae_title:$('connAe').value,url:$('connUrl').value});else c.path=$('connPath').value;return c}
async function saveConnection(){try{ensureDevice();selectedDevice=await api(`/api/v1/devices/${selectedDevice.id}/configuration`,{method:'PUT',body:JSON.stringify({connection:collectConnection()})});msg('Connection settings saved.');goStep(3)}catch(e){msg(e.message,false)}}
function activeProfile(){return (catalogData.profiles||[]).find(x=>x.id===(selectedDevice?.profile_id||$('profile').value))||{}}
function renderParserEditor(){const p=activeProfile(),cfg=selectedDevice?.config?.parser_config||p.config||{};$('parserSummary').innerHTML=`<b>${esc(p.parser||'')}</b> · ${esc(p.protocol||'')}<br><span class="muted">${esc(p.notes||'')}</span>`;['fixedWidthEditor','delimitedEditor','regexEditor'].forEach(id=>$(id).classList.add('hidden'));if(p.parser==='generic-fixed-width'||p.parser==='mindray-bc3000plus'){$('fixedWidthEditor').classList.remove('hidden');const a=cfg.accession_slice||[0,8];$('accessionStart').value=a[0];$('accessionEnd').value=a[1];$('fixedRows').innerHTML='';(cfg.fields||[]).forEach(addFixedRow)}else if(p.parser==='generic-delimited'){$('delimitedEditor').classList.remove('hidden');$('recordSeparator').value=cfg.record_separator||'\\r';$('fieldSeparator').value=cfg.field_separator||'|';$('sampleRecord').value=cfg.sample_record||'S';$('accessionIndex').value=cfg.accession_index??1;$('resultRecord').value=cfg.result_record||'R';$('resultIndexes').value=[cfg.code_index??1,cfg.value_index??2,cfg.unit_index??3,cfg.flag_index??4].join(',')}else if(p.parser==='generic-regex'){$('regexEditor').classList.remove('hidden');$('accessionRegex').value=cfg.accession_regex||'';$('resultRegex').value=cfg.result_regex||''}$('parserJson').value=''}
function addFixedRow(f={}){const tr=document.createElement('tr');tr.innerHTML=`<td><input class="fw-code" value="${esc(f.code||'')}"/></td><td><input class="fw-start" type="number" value="${esc(f.start??0)}"/></td><td><input class="fw-end" type="number" value="${esc(f.end??0)}"/></td><td><input class="fw-unit" value="${esc(f.unit||'')}"/></td><td><input class="fw-loinc" value="${esc(f.loinc||'')}"/></td><td><button class="danger" onclick="this.closest('tr').remove()">×</button></td>`;$('fixedRows').appendChild(tr)}
function collectParser(){const p=activeProfile();let cfg={};if(p.parser==='generic-fixed-width'||p.parser==='mindray-bc3000plus'){cfg.accession_slice=[+$('accessionStart').value,+$('accessionEnd').value];cfg.fields=[...$('fixedRows').querySelectorAll('tr')].map(tr=>({code:tr.querySelector('.fw-code').value,start:+tr.querySelector('.fw-start').value,end:+tr.querySelector('.fw-end').value,unit:tr.querySelector('.fw-unit').value||null,loinc:tr.querySelector('.fw-loinc').value||null})).filter(x=>x.code)}else if(p.parser==='generic-delimited'){const i=$('resultIndexes').value.split(',').map(x=>+x.trim());Object.assign(cfg,{record_separator:$('recordSeparator').value,field_separator:$('fieldSeparator').value,sample_record:$('sampleRecord').value,accession_index:+$('accessionIndex').value,result_record:$('resultRecord').value,code_index:i[0]??1,value_index:i[1]??2,unit_index:i[2]??3,flag_index:i[3]??4})}else if(p.parser==='generic-regex')Object.assign(cfg,{accession_regex:$('accessionRegex').value,result_regex:$('resultRegex').value});const advanced=$('parserJson').value.trim();if(advanced)Object.assign(cfg,JSON.parse(advanced));return cfg}
async function saveParser(){try{ensureDevice();const cfg=collectParser();selectedDevice=await api(`/api/v1/devices/${selectedDevice.id}/configuration`,{method:'PUT',body:JSON.stringify({parser_config:cfg})});msg('Parser configuration saved.');goStep(4)}catch(e){msg(e.message,false)}}
async function runPreview(){try{ensureDevice();let payload=$('previewPayload').value;const p=activeProfile();if(['json-result','fhir-bundle'].includes(p.parser)){try{payload=JSON.parse(payload)}catch{}}const body={payload,parser_config:collectParser(),record_success:true};const out=await api(`/api/v1/devices/${selectedDevice.id}/preview`,{method:'POST',body:JSON.stringify(body)});lastPreview=out.normalized;$('previewOutput').innerHTML=`<div class="success">Parse passed: accession <b>${esc(lastPreview.accession)}</b>, ${lastPreview.observations.length} observations.</div><div class="codebox">${esc(JSON.stringify(lastPreview,null,2))}</div>`;renderMapping(lastPreview.observations);selectedDevice=await api(`/api/v1/devices/${selectedDevice.id}`);renderGate()}catch(e){$('previewOutput').innerHTML=`<div class="error">${esc(e.message)}</div>`;msg(e.message,false)}}
function renderMapping(obs){const saved=selectedDevice?.config?.mapping||{};$('mappingRows').innerHTML=obs.map(o=>{const m=saved[o.code]||{};return `<tr data-source="${esc(o.code)}"><td><b>${esc(o.code)}</b><br><span class="muted">${esc(o.value)} ${esc(o.unit||'')}</span></td><td><input class="map-enabled" type="checkbox" ${m.enabled===false?'':'checked'}/></td><td><input class="map-code" value="${esc(m.code||o.code)}"/></td><td><input class="map-display" value="${esc(m.display||o.display||'')}"/></td><td><input class="map-loinc" value="${esc(m.loinc||o.loinc||'')}"/></td><td><input class="map-unit" value="${esc(m.unit||o.unit||'')}"/></td></tr>`}).join('');$('mappingEditor').classList.remove('hidden')}
function collectMapping(){const out={};[...$('mappingRows').querySelectorAll('tr')].forEach(tr=>{const s=tr.dataset.source;out[s]={enabled:tr.querySelector('.map-enabled').checked,code:tr.querySelector('.map-code').value,display:tr.querySelector('.map-display').value||null,loinc:tr.querySelector('.map-loinc').value||null,unit:tr.querySelector('.map-unit').value||null}});return out}
async function saveMapping(){try{ensureDevice();selectedDevice=await api(`/api/v1/devices/${selectedDevice.id}/configuration`,{method:'PUT',body:JSON.stringify({mapping:collectMapping()})});msg('Result mapping saved.');goStep(5)}catch(e){msg(e.message,false)}}
function renderGate(){if(!selectedDevice){$('gateState').innerHTML='<div class="error">Select a device first.</div>';return}const r=selectedDevice.delivery_gate_reason;$('gateState').innerHTML=r?`<div class="error"><b>Delivery locked:</b> ${esc(r)}</div>`:'<div class="success"><b>Delivery gate passed.</b> Automatic EMR delivery can be enabled after target configuration.</div>'}
async function saveValidation(){try{ensureDevice();selectedDevice=await api(`/api/v1/devices/${selectedDevice.id}/validation`,{method:'POST',body:JSON.stringify({status:$('validationStatus').value,validated_by:$('validatedBy').value||null,notes:$('validationNotes').value||null})});hydrateDevice();msg('Validation status saved.')}catch(e){msg(e.message,false)}}
async function saveDelivery(){try{ensureDevice();selectedDevice=await api(`/api/v1/devices/${selectedDevice.id}/delivery`,{method:'PUT',body:JSON.stringify({enabled:$('deliveryEnabled').value==='true',target_type:$('targetType').value,target:$('target').value})});hydrateDevice();msg('Delivery settings saved.')}catch(e){msg(e.message,false)}}
async function saveOrder(){try{await api('/api/v1/orders',{method:'POST',body:JSON.stringify({accession:$('orderAccession').value,patient_id:$('patientId').value,encounter_id:$('encounterId').value||null,service_request_id:$('serviceRequestId').value||null})});await loadOrders()}catch(e){alert(e.message)}}
async function loadOrders(){try{const rows=await api('/api/v1/orders');$('orderRows').innerHTML=rows.map(r=>`<tr><td>${esc(r.accession)}</td><td>${esc(r.patient_id)}</td><td>${esc(r.encounter_id||'')}</td><td>${esc(r.service_request_id||'')}</td></tr>`).join('')}catch{}}
async function loadResults(){try{window._results=await api('/api/v1/results');$('resultRows').innerHTML=window._results.map(r=>`<tr><td>${r.id}</td><td>${esc(r.device_key)}</td><td>${esc(r.accession)}</td><td>${esc(r.patient_id||'—')}</td><td>${validationPill(r.status)}</td><td>${esc(r.observed_at)}</td><td>${esc((r.observations||[]).map(x=>`${x.code}=${x.value}`).join(', '))}</td></tr>`).join('')}catch{}}
async function loadDeliveries(){try{window._deliveries=await api('/api/v1/deliveries');$('deliveryRows').innerHTML=window._deliveries.map(r=>`<tr><td>${r.id}</td><td>${r.result_id}</td><td>${esc(r.target_type)}<br><span class="muted">${esc(r.target)}</span></td><td>${r.attempt_no}</td><td>${validationPill(r.status)}</td><td>${esc(r.response_excerpt||'')}</td></tr>`).join('')}catch{}}
$('apiKey').value=key();renderConnectionFields();refreshAll();
</script>
</body></html>'''
